#import "FTPCommandClient.h"
#import <CFNetwork/CFNetwork.h>
@implementation FTPCommandClient
@synthesize delegate=_delegate;
- (id)init{self=[super init];if(self)_finished=YES;return self;}
- (void)dealloc{[self cancel];[_receiveData release];[_host release];[_username release];[_password release];[_path1 release];[_path2 release];[super dealloc];}
- (void)performAction:(FTPCommandAction)a host:(NSString *)h port:(NSInteger)p username:(NSString *)u password:(NSString *)pw path1:(NSString *)p1 path2:(NSString *)p2{
 [self cancel];_finished=NO;_state=0;_action=a;_port=p;[_host release];_host=[h copy];[_username release];_username=[u copy];[_password release];_password=[pw copy];[_path1 release];_path1=[p1 copy];[_path2 release];_path2=[p2 copy];[_receiveData release];_receiveData=[[NSMutableData alloc]init];
 CFReadStreamRef r=NULL;CFWriteStreamRef w=NULL;CFStreamCreatePairWithSocketToHost(NULL,(CFStringRef)_host,(UInt32)_port,&r,&w);if(!r||!w){if(r)CFRelease(r);if(w)CFRelease(w);[self failMessage:@"FTP kontrol bağlantısı açılamadı." code:4001];return;}
 _inputStream=(NSInputStream*)r;_outputStream=(NSOutputStream*)w;[_inputStream setDelegate:self];[_outputStream setDelegate:self];[_inputStream scheduleInRunLoop:[NSRunLoop mainRunLoop] forMode:NSDefaultRunLoopMode];[_outputStream scheduleInRunLoop:[NSRunLoop mainRunLoop] forMode:NSDefaultRunLoopMode];[_inputStream open];[_outputStream open];}
- (void)sendCommand:(NSString*)c{NSData*d=[[c stringByAppendingString:@"\r\n"] dataUsingEncoding:NSUTF8StringEncoding];const uint8_t*b=[d bytes];NSUInteger len=[d length],o=0;while(o<len){NSInteger n=[_outputStream write:&b[o] maxLength:len-o];if(n<=0)break;o+=(NSUInteger)n;}}
- (void)stream:(NSStream*)s handleEvent:(NSStreamEvent)e{if(_finished)return;if(s==_inputStream&&e==NSStreamEventHasBytesAvailable){uint8_t b[4096];NSInteger n=[_inputStream read:b maxLength:sizeof(b)];if(n>0){[_receiveData appendBytes:b length:(NSUInteger)n];[self processReplies];}}else if(e==NSStreamEventErrorOccurred){NSError*er=[s streamError];if(er)[self fail:er];else[self failMessage:@"FTP kontrol bağlantısı hatası." code:4002];}else if(e==NSStreamEventEndEncountered){if(!_finished)[self failMessage:@"FTP sunucusu bağlantıyı kapattı." code:4003];}}
- (void)processReplies{NSString*t=[[[NSString alloc]initWithData:_receiveData encoding:NSUTF8StringEncoding]autorelease];if(!t)return;NSRange r=[t rangeOfString:@"\n" options:NSBackwardsSearch];if(r.location==NSNotFound)return;NSString*c=[t substringToIndex:r.location+1];NSString*rem=[t substringFromIndex:r.location+1];[_receiveData setData:[rem dataUsingEncoding:NSUTF8StringEncoding]];for(NSString*raw in [c componentsSeparatedByCharactersInSet:[NSCharacterSet newlineCharacterSet]]){NSString*l=[raw stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];if([l length]<3)continue;NSInteger code=[[l substringToIndex:3] integerValue];if(code<100||code>599)continue;if([l length]>3&&[l characterAtIndex:3]=='-')continue;[self handleReply:code line:l];if(_finished)break;}}
- (void)handleReply:(NSInteger)code line:(NSString*)line{if(code>=400){[self failMessage:line code:code];return;}if(_state==0&&code==220){[self sendCommand:[NSString stringWithFormat:@"USER %@",[_username length]?_username:@"anonymous"]];_state=1;return;}if(_state==1){if(code==230){[self sendAction];return;}if(code==331){[self sendCommand:[NSString stringWithFormat:@"PASS %@",[_password length]?_password:@"anonymous@"]];_state=2;return;}}if(_state==2&&code==230){[self sendAction];return;}if(_action==FTPCommandActionRename){if(_state==10&&code==350){[self sendCommand:[NSString stringWithFormat:@"RNTO %@",_path2]];_state=11;return;}if(_state==11&&code>=200&&code<300){[self success];return;}}else if(_state==10&&code>=200&&code<300){[self success];}}
- (void)sendAction{if(_action==FTPCommandActionDeleteFile)[self sendCommand:[NSString stringWithFormat:@"DELE %@",_path1]];else if(_action==FTPCommandActionDeleteDirectory)[self sendCommand:[NSString stringWithFormat:@"RMD %@",_path1]];else if(_action==FTPCommandActionMakeDirectory)[self sendCommand:[NSString stringWithFormat:@"MKD %@",_path1]];else if(_action==FTPCommandActionRename)[self sendCommand:[NSString stringWithFormat:@"RNFR %@",_path1]];_state=10;}
- (void)success{FTPCommandAction a=_action;[self closeStreams];_finished=YES;if([_delegate respondsToSelector:@selector(ftpCommandClient:didFinishAction:)])[_delegate ftpCommandClient:self didFinishAction:a];}
- (void)failMessage:(NSString*)m code:(NSInteger)c{[self fail:[NSError errorWithDomain:@"iPad1FTPDownloader.Command" code:c userInfo:[NSDictionary dictionaryWithObject:m forKey:NSLocalizedDescriptionKey]]];}
- (void)fail:(NSError*)e{if(_finished)return;[self closeStreams];_finished=YES;if([_delegate respondsToSelector:@selector(ftpCommandClient:didFailWithError:)])[_delegate ftpCommandClient:self didFailWithError:e];}
- (void)closeStreams{if(_inputStream){[_inputStream close];[_inputStream removeFromRunLoop:[NSRunLoop mainRunLoop] forMode:NSDefaultRunLoopMode];[_inputStream setDelegate:nil];[_inputStream release];_inputStream=nil;}if(_outputStream){[_outputStream close];[_outputStream removeFromRunLoop:[NSRunLoop mainRunLoop] forMode:NSDefaultRunLoopMode];[_outputStream setDelegate:nil];[_outputStream release];_outputStream=nil;}}
- (void)cancel{[self closeStreams];_finished=YES;}
@end
